// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: accessinfo.proto

package log_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessType int32

const (
	AccessType_UNSPECIFIED AccessType = 0
	AccessType_WRITE_FILE  AccessType = 1
	AccessType_RENAME_FILE AccessType = 2
	AccessType_DELETE_FILE AccessType = 3
	AccessType_READ_FILE   AccessType = 4
	AccessType_CHMOD_FILE  AccessType = 5
	AccessType_LINK_FILE   AccessType = 6
)

// Enum value maps for AccessType.
var (
	AccessType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "WRITE_FILE",
		2: "RENAME_FILE",
		3: "DELETE_FILE",
		4: "READ_FILE",
		5: "CHMOD_FILE",
		6: "LINK_FILE",
	}
	AccessType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"WRITE_FILE":  1,
		"RENAME_FILE": 2,
		"DELETE_FILE": 3,
		"READ_FILE":   4,
		"CHMOD_FILE":  5,
		"LINK_FILE":   6,
	}
)

func (x AccessType) Enum() *AccessType {
	p := new(AccessType)
	*p = x
	return p
}

func (x AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_accessinfo_proto_enumTypes[0].Descriptor()
}

func (AccessType) Type() protoreflect.EnumType {
	return &file_accessinfo_proto_enumTypes[0]
}

func (x AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessType.Descriptor instead.
func (AccessType) EnumDescriptor() ([]byte, []int) {
	return file_accessinfo_proto_rawDescGZIP(), []int{0}
}

type AccessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessType  AccessType `protobuf:"varint,1,opt,name=access_type,json=accessType,proto3,enum=pds.pb.AccessType" json:"access_type,omitempty"`
	FilePath    string     `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize    uint64     `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ProcessName string     `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessId   uint32     `protobuf:"varint,5,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
}

func (x *AccessInfo) Reset() {
	*x = AccessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accessinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessInfo) ProtoMessage() {}

func (x *AccessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_accessinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessInfo.ProtoReflect.Descriptor instead.
func (*AccessInfo) Descriptor() ([]byte, []int) {
	return file_accessinfo_proto_rawDescGZIP(), []int{0}
}

func (x *AccessInfo) GetAccessType() AccessType {
	if x != nil {
		return x.AccessType
	}
	return AccessType_UNSPECIFIED
}

func (x *AccessInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AccessInfo) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *AccessInfo) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *AccessInfo) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

var File_accessinfo_proto protoreflect.FileDescriptor

var file_accessinfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x64, 0x73, 0x2e, 0x70, 0x62, 0x22, 0xbd, 0x01, 0x0a, 0x0a, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x0b, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x64, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x2a, 0x7d, 0x0a, 0x0a, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x52, 0x49,
	0x54, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x4e,
	0x41, 0x4d, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x48,
	0x4d, 0x4f, 0x44, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x49,
	0x4e, 0x4b, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x06, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x62, 0x2f,
	0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accessinfo_proto_rawDescOnce sync.Once
	file_accessinfo_proto_rawDescData = file_accessinfo_proto_rawDesc
)

func file_accessinfo_proto_rawDescGZIP() []byte {
	file_accessinfo_proto_rawDescOnce.Do(func() {
		file_accessinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_accessinfo_proto_rawDescData)
	})
	return file_accessinfo_proto_rawDescData
}

var file_accessinfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_accessinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_accessinfo_proto_goTypes = []interface{}{
	(AccessType)(0),    // 0: pds.pb.AccessType
	(*AccessInfo)(nil), // 1: pds.pb.AccessInfo
}
var file_accessinfo_proto_depIdxs = []int32{
	0, // 0: pds.pb.AccessInfo.access_type:type_name -> pds.pb.AccessType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accessinfo_proto_init() }
func file_accessinfo_proto_init() {
	if File_accessinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accessinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accessinfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accessinfo_proto_goTypes,
		DependencyIndexes: file_accessinfo_proto_depIdxs,
		EnumInfos:         file_accessinfo_proto_enumTypes,
		MessageInfos:      file_accessinfo_proto_msgTypes,
	}.Build()
	File_accessinfo_proto = out.File
	file_accessinfo_proto_rawDesc = nil
	file_accessinfo_proto_goTypes = nil
	file_accessinfo_proto_depIdxs = nil
}
